### ISSUE TITLE
Style `colorful.json` is missing attribution information

### ISSUE THREAD

**Issue by uwekamper** [versatiles-org/versatiles-org.github.io#1]
The style JSON found at `https://tile.versatiles.org/styles/colorful.json` does not include attribution information.

The following code will shoe NO attribution information:
```
new maplibregl.Map({
  container: 'map',
  style: 'https://tiles.versatiles.org/styles/colorful.json'
})
```

Screenshot:

![image](https://github.com/versatiles-org/versatiles-org.github.io/assets/829305/529ef2f4-f870-4eab-92ca-1bfd1a8dd403)

Possible workaround: You can use the styles JSON used on the versatiles.org website:

```
new maplibregl.Map({
  container: 'map',
  style: 'https://versatiles.org/assets/colorful.json'
})
```

With this code, the attribution is showing up. on the lower right:

![image](https://github.com/versatiles-org/versatiles-org.github.io/assets/829305/b705b620-3877-4599-b56f-7d9049707a83)

**Comment by MichaelKreil** [comment]
fixed it: https://tiles.versatiles.org/assets/styles/colorful.json
Thank you :)
